# ## python para desenvolvimento

# ! ## STAGE 1 - Maquina para armazenar as ferramentas
FROM python:3 AS environment-python-tools

WORKDIR /app

RUN python -m venv .

# TOOLS
RUN pip install pyvis
RUN pip install PyPDF2
RUN pip install fastapi

## DATABASE
RUN pip install unicorn
RUN pip install postgres
RUN pip install chromadb
RUN pip install pysqlite3
RUN pip install onnxruntime

## MACHINE LEARN
RUN pip install nltk
RUN pip install numpy
RUN pip install keras
RUN pip install pandas
RUN pip install scikit-learn

## LLM
RUN pip install ollama
RUN pip install openai
RUN pip install langchain
RUN pip install tokenizers
RUN pip install langchain-openai

## PLOT
RUN pip install plot
RUN pip install matplot

# ! ## STAGE 1 - Maquina para armazenar as dependencias
FROM environment-python-tools AS environment-python-dependences

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# ! ## STAGE 3 - Maquina para excutar o ambiente de desenvolvimento
FROM environment-python-dependences AS environment-python-dev

WORKDIR /app

COPY . ./

VOLUME [ "/app/data", "/app/bookcase", "/app/lexicon", "/app/library", "/app/viz" ]

CMD [ "python", "./main.py" ]