# flake8:noqa: E501

stopwords_pt = [
    # Stopwords em português do Brasil
    "a", "à", "ao", "aos", "as", "às", "de", "do", "da", "dos", "das", "em", "no", "na", "nos", "nas",
    "por", "pelos", "pela", "pelas", "o", "os", "um", "uns", "uma", "umas", "e", "é", "que", "com",
    "se", "não", "para", "como", "mais", "mas", "ou", "quando", "muito", "já", "era", "são", "seu",
    "sua", "seus", "suas", "me", "minha", "meu", "meus", "minhas", "este", "estes", "esta", "estas",
    "esse", "esses", "essa", "essas", "isto", "isso", "aquilo", "aquele", "aquela", "aqueles",
    "aquelas", "ele", "ela", "eles", "elas", "nos", "lhe", "lhes",
    "sobre", "também", "pelo", "pela", "entre", "depois", "sem", "mesmo", "ainda", "seu", "sua",
    "onde", "durante", "após", "contra", "todos", "todas", "além", "nem", "até", "desde", "tanto",
    "cada", "pouco", "antes", "porque", "assim", "dessa", "desse", "disto", "disso", "daquele",
    "daquela", "daquilo", "neste", "nesta", "nisto", "naquele", "naquela", "tudo", "todos", "todas",
    "qual", "quais", "quem", "cujo", "cujos", "cuja", "cujas", "quanto", "quantos", "quantas",
    "qualquer", "porém", "entretanto", "todavia", "pois", "portanto", "contudo", "então", "depois",
    "antes", "agora", "sempre", "nunca", "já", "logo", "aqui", "ali", "lá", "cá", "bem", "mal",
    "hoje", "amanhã", "ontem", "agora", "depois", "antes", "acima", "abaixo", "dentro", "fora",
    "daí", "aí", "daqui", "por que", "por quê", "para que", "por onde", "quando", "como", "porque",
    "se", "caso", "desde que", "embora", "apesar", "mesmo que", "posto que", "logo que", "assim que",
    "enquanto", "até que", "conforme", "segundo", "consoante", "talvez", "afinal", "certo", "bastante",
    "demais", "novo", "nova", "novos", "novas", "algum", "alguma", "alguns", "algumas", "nenhum",
    "nenhuma", "nada", "tudo", "tanto", "outra", "outro", "outras", "outros", "quase", "puder",
    "puderam", "podem", "pode", "poder", "podendo", "podia", "podiam", "poisé", "poisé", "perto",
    "longe", "desde", "durante", "sobre", "trás", "atrás", "frente", "apenas", "só", "somente",
    "comigo", "contigo", "consigo", "conosco", "convosco", "cada", "muito", "pouco", "demais",
    "bastante", "quanto", "muitos", "poucos", "tantos", "vários", "que", "qual", "qualquer",
    "quaisquer", "tal", "tais", "afinal", "apesar", "eis", "mas", "menos", "ou", "também", "além",
    "antes", "porque", "portanto", "seja", "será", "são", "tanto", "ter", "tive", "tido", "tinha",
    "tinham", "tendo", "tem", "têm", "tenho", "terá", "terão", "teu", "teus", "toda", "todas",
    "todo", "todos", "vai", "vão", "você", "vocês", "vos", "vossa", "vosso", "é", "fui", "foi",
    "foram", "está", "estão", "estive", "estava", "estavam", "estávamos", "esteve", "estivemos",
    "estevam", "estivéramos", "estivéssemos", "haja", "havemos", "houver", "houvesse", "houvessem",
    "houve", "houvemos", "houveram", "houverá", "houverão", "houveria", "houveriam", "houvermos",
    "houvermos", "há", "havendo", "hão", "he", "hei", "hoje", "hontem", "ora", "parar", "primeiro",
    "primeira", "primeiros", "primeiras", "próximo", "próximos", "próximas", "qual", "quando", "quanto",
    "quantos", "se", "ser", "serei", "seremos", "seria", "seriam", "seu", "seus", "suas", "tua",
    "tuas", "tudo", "um", "uma", "vários", "vez", "vezes", "ver", "vem", "vêm", "vindo", "vinha",
    "vinham", "vir", "vou", "ir", "vai", "vão", "fazer", "fez", "fiz", "fizeram", "fizer", "fizemos",
    "houver", "tiver", "ter", "por", "pelo", "pelos", "pela", "pelas",
]